services:
  web:
    build: .
    ports:
      - "8000:80"
    environment:
      - APACHE_RUN_USER=www-data
      - APACHE_RUN_GROUP=www-data
    command: >
      bash -c "composer install --no-interaction --prefer-dist --optimize-autoloader
      && apache2-foreground"
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: products
    volumes:
      - ./mysql-init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3307:3306"