apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: herlandio7/manager-products:latest
        ports:
        - containerPort: 8000
        envFrom:
          - secretRef:
              name: db-secret
          - configMapRef:
              name: web-config
        command: ["/bin/bash", "-c", "composer install --no-interaction --prefer-dist --optimize-autoloader && apache2-foreground"]
        volumeMounts:
        - name: web-volume
          mountPath: /var/www/html/manager-products
      volumes:
      - name: web-volume
        persistentVolumeClaim:
          claimName: web-pvc
