apiVersion: v1
kind: Service
metadata:
  name: web-service
spec:
  type: NodePort
  ports:
  - port: 8000               
    targetPort: 80           
    nodePort: 30001          
    protocol: TCP
  selector:
    app: web